apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform.fullname" . }}-config
  labels:
    {{- include "platform.labels" . | nindent 4 }}
data:
  PLATFORM_MODE: {{ .Values.config.mode | quote }}
  PLATFORM_GATEWAY_CONTROL_URL: {{ .Values.config.controlUrl | quote }}
  PLATFORM_GATEWAY_SYNC_INTERVAL: {{ .Values.config.syncInterval | quote }}
