"""Initial platform and billing schema

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_audit",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=200), nullable=False),
        sa.Column("details", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "billing_entries",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("transaction_id", sa.String(length=64), nullable=False),
        sa.Column("account", sa.String(length=64), nullable=False),
        sa.Column(
            "amount",
            sa.Numeric(30, 12).with_variant(sa.String(64), "sqlite"),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "billing_quotas",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=False),
        sa.Column("rpm", sa.Integer(), nullable=True),
        sa.Column("tpm", sa.Integer(), nullable=True),
        sa.Column("concurrent", sa.Integer(), nullable=True),
        sa.Column(
            "max_budget",
            sa.Numeric(30, 12).with_variant(sa.String(64), "sqlite"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "scope", "subject_id"),
    )
    op.create_table(
        "billing_reconciliations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("call_id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "call_id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key"),
    )
    op.create_table(
        "billing_reservations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("call_id", sa.String(length=64), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "amount",
            sa.Numeric(30, 12).with_variant(sa.String(64), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "input_price",
            sa.Numeric(30, 12).with_variant(sa.String(64), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "output_price",
            sa.Numeric(30, 12).with_variant(sa.String(64), "sqlite"),
            nullable=False,
        ),
        sa.Column("estimated_input_tokens", sa.Integer(), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("rate_tokens", sa.BigInteger(), nullable=False),
        sa.Column("rate_scopes", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "cost",
            sa.Numeric(30, 12).with_variant(sa.String(64), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "actual_cost",
            sa.Numeric(30, 12).with_variant(sa.String(64), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "overage",
            sa.Numeric(30, 12).with_variant(sa.String(64), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "provider_cost",
            sa.Numeric(30, 12).with_variant(sa.String(64), "sqlite"),
            nullable=True,
        ),
        sa.Column("raw_usage", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "call_id"),
    )
    with op.batch_alter_table("billing_reservations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_billing_reservations_tenant_created",
            ["tenant_id", "created_at"],
            unique=False,
        )

    op.create_table(
        "billing_transactions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column(
            "amount",
            sa.Numeric(30, 12).with_variant(sa.String(64), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "balance",
            sa.Numeric(30, 12).with_variant(sa.String(64), "sqlite"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("call_id", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "type", "call_id"),
        sa.UniqueConstraint("tenant_id", "type", "idempotency_key"),
    )
    op.create_table(
        "billing_wallets",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column(
            "balance",
            sa.Numeric(30, 12).with_variant(sa.String(64), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "reserved",
            sa.Numeric(30, 12).with_variant(sa.String(64), "sqlite"),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("blocked", sa.Boolean(), nullable=False),
        sa.Column("block_reason", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_table(
        "platform_audits",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("actor_email", sa.String(length=254), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("platform_audits", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_platform_audits_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "platform_auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    with op.batch_alter_table("platform_auth_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_platform_auth_sessions_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "platform_calls",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("agent_name", sa.String(length=120), nullable=False),
        sa.Column("user_email", sa.String(length=254), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost", sa.String(length=40), nullable=False),
        sa.Column("provider_cost", sa.String(length=40), nullable=True),
        sa.Column("price_version", sa.Integer(), nullable=False),
        sa.Column("raw_usage", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("finished_at", sa.String(length=40), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("platform_calls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_platform_calls_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_platform_calls_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            "platform_calls_tenant_date", ["tenant_id", "created_at"], unique=False
        )

    op.create_table(
        "platform_login_attempts",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("window", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "platform_messages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "role"),
    )
    with op.batch_alter_table("platform_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_platform_messages_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_platform_messages_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "platform_models",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("input_price", sa.String(length=40), nullable=False),
        sa.Column("output_price", sa.String(length=40), nullable=False),
        sa.Column("context_window", sa.Integer(), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=False),
        sa.Column("price_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "alias"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("platform_models", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_platform_models_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "platform_run_events",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "sequence"),
    )
    op.create_table(
        "platform_tenants",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "platform_users",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("platform_users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_platform_users_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "platform_agents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("max_steps", sa.Integer(), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("tools", sa.JSON(), nullable=False),
        sa.Column("published_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "model_id"],
            ["platform_models.tenant_id", "platform_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("platform_agents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_platform_agents_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "platform_agent_versions",
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id"],
            ["platform_agents.tenant_id", "platform_agents.id"],
        ),
        sa.PrimaryKeyConstraint("agent_id", "version"),
    )
    op.create_table(
        "platform_sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id"],
            ["platform_agents.tenant_id", "platform_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "user_id"],
            ["platform_users.tenant_id", "platform_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("platform_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_platform_sessions_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "platform_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("agent_name", sa.String(length=120), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=True),
        sa.Column("lease_until", sa.Float(), nullable=True),
        sa.Column("deadline", sa.Float(), nullable=True),
        sa.Column("fence", sa.Integer(), nullable=False),
        sa.Column("finished_at", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "session_id"],
            ["platform_sessions.tenant_id", "platform_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "user_id", "idempotency_key"),
    )
    with op.batch_alter_table("platform_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_platform_runs_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_platform_runs_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_platform_runs_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            "platform_runs_tenant_date", ["tenant_id", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("platform_runs", schema=None) as batch_op:
        batch_op.drop_index("platform_runs_tenant_date")
        batch_op.drop_index(batch_op.f("ix_platform_runs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_platform_runs_status"))
        batch_op.drop_index(batch_op.f("ix_platform_runs_session_id"))

    op.drop_table("platform_runs")
    with op.batch_alter_table("platform_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_platform_sessions_tenant_id"))

    op.drop_table("platform_sessions")
    op.drop_table("platform_agent_versions")
    with op.batch_alter_table("platform_agents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_platform_agents_tenant_id"))

    op.drop_table("platform_agents")
    with op.batch_alter_table("platform_users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_platform_users_tenant_id"))

    op.drop_table("platform_users")
    op.drop_table("platform_tenants")
    op.drop_table("platform_run_events")
    with op.batch_alter_table("platform_models", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_platform_models_tenant_id"))

    op.drop_table("platform_models")
    with op.batch_alter_table("platform_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_platform_messages_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_platform_messages_session_id"))

    op.drop_table("platform_messages")
    op.drop_table("platform_login_attempts")
    with op.batch_alter_table("platform_calls", schema=None) as batch_op:
        batch_op.drop_index("platform_calls_tenant_date")
        batch_op.drop_index(batch_op.f("ix_platform_calls_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_platform_calls_run_id"))

    op.drop_table("platform_calls")
    with op.batch_alter_table("platform_auth_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_platform_auth_sessions_user_id"))

    op.drop_table("platform_auth_sessions")
    with op.batch_alter_table("platform_audits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_platform_audits_tenant_id"))

    op.drop_table("platform_audits")
    op.drop_table("billing_wallets")
    op.drop_table("billing_transactions")
    with op.batch_alter_table("billing_reservations", schema=None) as batch_op:
        batch_op.drop_index("ix_billing_reservations_tenant_created")

    op.drop_table("billing_reservations")
    op.drop_table("billing_reconciliations")
    op.drop_table("billing_quotas")
    op.drop_table("billing_entries")
    op.drop_table("billing_audit")
    # ### end Alembic commands ###
