"""State contracts and domain models for the subgraph interrupt demo."""

from __future__ import annotations

import operator
from typing import Annotated, Literal, TypedDict

from pydantic import BaseModel, Field, model_validator

BranchName = Literal["content", "compliance", "delivery"]
DecisionType = Literal["approve", "edit", "reject"]
ResultStatus = Literal["approved", "edited", "rejected"]


class ReviewRequest(BaseModel):
    """The immutable release request read by all three review subgraphs."""

    topic: str = Field(min_length=1)
    content: str = Field(min_length=1)
    target_channel: str = Field(min_length=1)
    scheduled_at: str = Field(min_length=1)


class ReviewProposal(BaseModel):
    """A branch-specific proposal that must be reviewed by a human."""

    branch: BranchName
    title: str
    proposed_value: str
    notes: list[str] = Field(default_factory=list)


class GeneratedProposal(BaseModel):
    """Structured content generated by the real model for one review branch."""

    title: str = Field(min_length=1, description="简短的中文审核标题")
    proposed_value: str = Field(
        min_length=1,
        description="提交给人工审核的完整方案，不要使用占位符",
    )
    notes: list[str] = Field(
        default_factory=list,
        description="需要人工重点确认的事实、风险或假设",
    )


class ReviewDecision(BaseModel):
    """A normalized human response returned to an interrupt."""

    type: DecisionType
    replacement: str | None = None
    reason: str | None = None

    @model_validator(mode="after")
    def validate_decision(self) -> ReviewDecision:
        if self.type == "edit" and not (self.replacement or "").strip():
            raise ValueError("edit 决定必须提供 replacement")
        if self.type == "reject" and not (self.reason or "").strip():
            raise ValueError("reject 决定必须提供 reason")
        return self


class ReviewResult(BaseModel):
    branch: BranchName
    status: ResultStatus
    original_value: str
    final_value: str | None
    reason: str | None = None


class AuditEvent(BaseModel):
    branch: BranchName | Literal["parent"]
    stage: str
    message: str


class ReviewSummary(BaseModel):
    ready_to_publish: bool
    approved_count: int = Field(ge=0)
    edited_count: int = Field(ge=0)
    rejected_count: int = Field(ge=0)
    results: list[ReviewResult]
    message: str
    # The post-review value for downstream publishing. The original proposal
    # remains available in ReviewResult.original_value for audit purposes.
    publish_content: str | None = None


class ParentInput(TypedDict):
    request: ReviewRequest


class ParentState(ParentInput, total=False):
    """Only reducer-backed fields may be written by parallel subgraphs."""

    review_results: Annotated[list[ReviewResult], operator.add]
    audit_events: Annotated[list[AuditEvent], operator.add]
    final_summary: ReviewSummary


class ReviewSubgraphInput(TypedDict):
    request: ReviewRequest


class ReviewSubgraphOutput(TypedDict, total=False):
    review_results: Annotated[list[ReviewResult], operator.add]
    audit_events: Annotated[list[AuditEvent], operator.add]


class ReviewSubgraphState(ReviewSubgraphInput, ReviewSubgraphOutput, total=False):
    """Proposal and decision are private and never leak into parent state."""

    proposal: ReviewProposal
    decision: ReviewDecision
