apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "litellm.fullname" . }}-config
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
data:
  litellm.yaml: |
    {{- tpl (.Files.Get "files/litellm.yaml") . | nindent 4 }}
